version: "3.9"
services:
  shopping_store_process_api:
    image: shopping_store_process_api:latest
    container_name: 'shopping_store_process_api'
    restart: always
    expose:
      - 5001
    ports:
      - 5001:5001
    volumes:
      - ./:/usr/src/app
networks:
  default:
    name: proxy